# Generated by Django 5.2b1 on 2025-02-27 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('size_from', models.IntegerField(default=0)),
                ('size_to', models.IntegerField(default=0)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Fuck It'), (2, 'Interested'), (3, 'Hyped')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.IntegerField(choices=[(1, 'No Fluff'), (2, 'Just Join It'), (3, 'Pracuj')])),
                ('original_id', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('seniority', models.CharField(blank=True, max_length=256)),
                ('salary_text', models.CharField(blank=True, max_length=256)),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Fuck It'), (2, 'Interested'), (3, 'Hyped')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lena_comparibility', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.company')),
            ],
        ),
    ]
